FROM adoptopenjdk/openjdk11:alpine-jre

# Simply the artifact path
ARG artifact=target/spring-boot-web.jar

WORKDIR /opt/app

COPY ${artifact} devops-integration.jar

# This should not be changed
ENTRYPOINT ["java","-jar","devops-integration.jar"]